version: '3'
services:
  python:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: python
    hostname: python
    # restart: always
    # volumes:
    #   - type: bind
    #     source: "/mnt/c/Users/rouni/OneDrive/Documents/Scripts/Python Scripts"
    #     target: "/project_dir"
    volumes:
      - "/mnt/c/Users/rouni/OneDrive/Documents/Scripts/Python Scripts:/project_dir"
      - "/mnt/h/共有ドライブ/勝木論文作成:/article_dir"
      - "/mnt/h/マイドライブ/Colab Notebooks/Output/Kimura_Fujisawa/kimura ablation index:/kimufuji"
    tty: true # これが無いと勝手に落ちちゃう。docker run の-itに相当する https://zukucode.com/2019/07/docker-ubuntu-tty.html